import { __ } from '@wordpress/i18n';
import { getUuid, showLicensePage } from '.';

export const SCENARIOS = [
	{
		title: __( 'Cart Weight-based shipping', 'easy-min-max' ),
		description: __(
			"A sample scenario of weight-based shipping. You can easily customize to fit your store's requirements.",
			'easy-min-max'
		),
		pro: false,
		tableData: {
			headers: [ 'Cart Weight', 'Shipping Cost' ],
			rows: [
				[ '0.01 – 5 kg', '$10' ],
				[ '5.01 – 10 kg', '$12' ],
				[ '10.01 kg or more', '$30' ],
			],
		},
		getRateData: () => [
			{
				id: getUuid(),
				type: 'fixed',
				initialValue: '10',
				everyValue: 0,
				thenValue: 0,
				firstValue: 0,
				basedOn: 'Cart:cart_quantity',
				conditions: [
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_weight',
						operator: 'between',
						value: '',
						min_range: '',
						max_range: '10',
					},
				],
			},
			{
				id: getUuid(),
				type: 'fixed',
				initialValue: '12',
				everyValue: 0,
				thenValue: 0,
				firstValue: 0,
				basedOn: 'Cart:cart_quantity',
				conditions: [
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_weight',
						operator: 'between',
						value: '',
						min_range: '5.01',
						max_range: '10',
					},
				],
			},
			{
				id: getUuid(),
				type: 'fixed',
				initialValue: '30',
				everyValue: 0,
				thenValue: 0,
				firstValue: 0,
				basedOn: 'Cart:cart_quantity',
				conditions: [
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_weight',
						operator: 'between',
						value: '',
						min_range: '10.01',
						max_range: '',
					},
				],
			},
		],
	},

	{
		title: __( 'Cart Quantity-based Shipping', 'easy-min-max' ),
		description: __(
			'Here’s an example scenario for setting up shipping rates based on the total quantity of items in the cart.',
			'easy-min-max'
		),
		pro: false,
		tableData: {
			headers: [ 'Cart Quantity', 'Shipping Cost' ],
			rows: [
				[ '1 – 3', '$8' ],
				[ '4 – 7', '$12' ],
				[ '8 or more', '$20' ],
			],
		},
		getRateData: () => [
			{
				id: getUuid(),
				type: 'fixed',
				initialValue: '8',
				everyValue: 0,
				thenValue: 0,
				firstValue: 0,
				basedOn: 'Cart:cart_quantity',
				conditions: [
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_quantity',
						operator: 'between',
						value: '',
						min_range: '1',
						max_range: '3',
					},
				],
			},
			{
				id: getUuid(),
				type: 'fixed',
				initialValue: '12',
				everyValue: 0,
				thenValue: 0,
				firstValue: 0,
				basedOn: 'Cart:cart_quantity',
				conditions: [
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_quantity',
						operator: 'between',
						value: '',
						min_range: '4',
						max_range: '7',
					},
				],
			},
			{
				id: getUuid(),
				type: 'fixed',
				initialValue: '20',
				everyValue: 0,
				thenValue: 0,
				firstValue: 0,
				basedOn: 'Cart:cart_quantity',
				conditions: [
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_quantity',
						operator: 'between',
						value: '',
						min_range: '8',
						max_range: '',
					},
				],
			},
		],
	},

	{
		title: __( 'Country + Cart Weight', 'easy-min-max' ),
		description: __(
			'This example shows a combination of country-based rules with cart-weight conditions to set precise shipping rates.',
			'easy-min-max'
		),
		pro: true,
		tableData: {
			headers: [ 'Country', 'Cart Weight', 'Shipping Cost' ],
			rows: [
				[ 'USA', '1 – 5 kg', '$10' ],
				[ 'USA', '5.01 – 10 kg', '$15' ],
				[ 'USA', '10.01 kg or more', '$30' ],
				[ 'UK', '1 – 5 kg', '$12' ],
				[ 'UK', '5.01 – 10 kg', '$18' ],
				[ 'UK', '10.01 kg or more', '$49' ],
			],
		},
		getRateData: () => [
			{
				id: getUuid(),
				type: 'fixed',
				initialValue: '10',
				everyValue: 0,
				thenValue: 0,
				firstValue: 0,
				basedOn: 'Cart:cart_quantity',
				conditions: [
					{
						id: getUuid(),
						type: 'Location',
						field: 'country',
						operator: 'equal',
						value: [ 'US' ],
						min_range: '',
						max_range: '',
					},
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_weight',
						operator: 'between',
						value: '',
						min_range: '0.01',
						max_range: '5',
					},
				],
			},
			{
				id: getUuid(),
				type: 'fixed',
				initialValue: '15',
				everyValue: 0,
				thenValue: 0,
				firstValue: 0,
				basedOn: 'Cart:cart_quantity',
				conditions: [
					{
						id: getUuid(),
						type: 'Location',
						field: 'country',
						operator: 'equal',
						value: [ 'US' ],
						min_range: '',
						max_range: '',
					},
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_weight',
						operator: 'between',
						value: '',
						min_range: '5.01',
						max_range: '10',
					},
				],
			},
			{
				id: getUuid(),
				type: 'fixed',
				initialValue: '30',
				everyValue: 0,
				thenValue: 0,
				firstValue: 0,
				basedOn: 'Cart:cart_quantity',
				conditions: [
					{
						id: getUuid(),
						type: 'Location',
						field: 'country',
						operator: 'equal',
						value: [ 'US' ],
						min_range: '',
						max_range: '',
					},
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_weight',
						operator: 'between',
						value: '',
						min_range: '10.01',
						max_range: '',
					},
				],
			},
			{
				id: getUuid(),
				type: 'fixed',
				initialValue: '12',
				everyValue: 0,
				thenValue: 0,
				firstValue: 0,
				basedOn: 'Cart:cart_quantity',
				conditions: [
					{
						id: getUuid(),
						type: 'Location',
						field: 'country',
						operator: 'equal',
						value: [ 'GB' ],
						min_range: '',
						max_range: '',
					},
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_weight',
						operator: 'between',
						value: '',
						min_range: '0.01',
						max_range: '5',
					},
				],
			},
			{
				id: getUuid(),
				type: 'fixed',
				initialValue: '18',
				everyValue: 0,
				thenValue: 0,
				firstValue: 0,
				basedOn: 'Cart:cart_quantity',
				conditions: [
					{
						id: getUuid(),
						type: 'Location',
						field: 'country',
						operator: 'equal',
						value: [ 'GB' ],
						min_range: '',
						max_range: '',
					},
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_weight',
						operator: 'between',
						value: '',
						min_range: '5.01',
						max_range: '10',
					},
				],
			},
			{
				id: getUuid(),
				type: 'fixed',
				initialValue: '49',
				everyValue: 0,
				thenValue: 0,
				firstValue: 0,
				basedOn: 'Cart:cart_quantity',
				conditions: [
					{
						id: getUuid(),
						type: 'Location',
						field: 'country',
						operator: 'equal',
						value: [ 'GB' ],
						min_range: '',
						max_range: '',
					},
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_weight',
						operator: 'between',
						value: '',
						min_range: '10.01',
						max_range: '',
					},
				],
			},
		],
	},

	{
		title: __( 'Country + Weight with Variable Charges', 'easy-min-max' ),
		description: __(
			'This example shows a combination of country-based rules, weight ranges, and flexible variable charges.',
			'easy-min-max'
		),
		pro: true,
		tableData: {
			headers: [ 'Country', 'Cart Weight', 'Shipping Cost' ],
			rows: [
				[ 'Canada', '0.01 - 100kg', '$12 + $1.5 per kg' ],
				[ 'UK', '0.01 - 100kg', '$14 + $2 per kg' ],
			],
		},
		getRateData: () => [
			{
				id: getUuid(),
				type: 'fixed_incremental',
				initialValue: '12',
				everyValue: '1',
				thenValue: '1.5',
				firstValue: '0',
				basedOn: 'Cart:cart_weight',
				conditions: [
					{
						id: getUuid(),
						type: 'Location',
						field: 'country',
						operator: 'equal',
						value: [ 'CA' ],
						min_range: '',
						max_range: '',
					},
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_weight',
						operator: 'between',
						value: '',
						min_range: '0.01',
						max_range: '100',
					},
				],
			},
			{
				id: getUuid(),
				type: 'fixed_incremental',
				initialValue: '14',
				everyValue: '1',
				thenValue: '2',
				firstValue: '0',
				basedOn: 'Cart:cart_weight',
				conditions: [
					{
						id: getUuid(),
						type: 'Location',
						field: 'country',
						operator: 'equal',
						value: [ 'GB' ],
						min_range: '',
						max_range: '',
					},
					{
						id: getUuid(),
						type: 'Cart',
						field: 'cart_weight',
						operator: 'between',
						value: '',
						min_range: '0.01',
						max_range: '100',
					},
				],
			},
		],
	},
];

export const CALCULATION_METHOD_OPTIONS = [
	{
		label: __( 'Manual Rates', 'easy-min-max' ),
		value: 'general',
		help: __(
			'Selecting this option lets you set your preferred conditions for manually calculating shipping rates.',
			'easy-min-max'
		),
	},
	{
		label: __( 'Carrier Live Rates (Beta)', 'easy-min-max' ),
		value: 'carrier',
		pro: true,
		help: __(
			"Selecting this option will help you choose and configure your preferred shipping carrier so that the shipping rate will be calculated in real time via the carrier's API.",
			'easy-min-max'
		),
	},
];

export const SHIPPING_METHOD_TYPE_OPTIONS = [
	{
		label: __( 'Flexible Rate', 'easy-min-max' ),
		value: 'flexible_amount',
		color: 'blue',
	},
	{
		label: __( 'Flat Rate', 'easy-min-max' ),
		value: 'flat_amount',
		color: 'orange',
	},
	{
		label: __( 'Free Shipping', 'easy-min-max' ),
		value: 'free_shipping',
		color: 'green',
	},
];

export const DAYS_OF_WEEK = [
	{
		value: '0',
		label: __( 'Sunday', 'easy-min-max' ),
	},
	{
		value: '1',
		label: __( 'Monday', 'easy-min-max' ),
	},
	{
		value: '2',
		label: __( 'Tuesday', 'easy-min-max' ),
	},
	{
		value: '3',
		label: __( 'Wednesday', 'easy-min-max' ),
	},
	{
		value: '4',
		label: __( 'Thursday', 'easy-min-max' ),
	},
	{
		value: '5',
		label: __( 'Friday', 'easy-min-max' ),
	},
	{
		value: '6',
		label: __( 'Saturday', 'easy-min-max' ),
	},
];

export const TAX_STATUS_OPTIONS = [
	{ value: 'taxable', label: __( 'Taxable', 'easy-min-max' ) },
	{ value: 'none', label: __( 'None', 'easy-min-max' ) },
];

export const SCENARIO_VISIBILITY_BASE_OPTIONS = [
	{
		value: 'logged_in',
		label: __( 'Logged-In Users', 'easy-min-max' ),
	},
	{
		value: 'logged_out',
		label: __( 'Logged-Out Users', 'easy-min-max' ),
	},
	{ value: 'both', label: __( 'Everyone', 'easy-min-max' ) },
];

export const HANDLING_FEE_OPTIONS = [
	{ value: 'fixed', label: __( 'Fixed Amount', 'easy-min-max' ) },
	{
		value: 'percentage',
		label: __( 'Percentage', 'easy-min-max' ),
	},
];

export const APPLY_HANDLING_TO_OPTIONS = [
	{
		value: 'entire_order',
		label: __( 'Entire Order', 'easy-min-max' ),
	},
	{ value: 'per_item', label: __( 'Per Item', 'easy-min-max' ) },
	// { value: 'per_package', label: 'Per Package' }, // TODO @samin: Add this when implementing carriers.
];

export const FLAT_RATE_CALCULATION_TYPE_OPTIONS = [
	{
		value: 'per_class',
		label: __(
			'Per Class: Charge shipping for each shipping class individually.',
			'easy-min-max'
		),
	},
	{
		value: 'per_order',
		label: __(
			'Per Order: Charge shipping for the most expensive shipping class.',
			'easy-min-max'
		),
	},
];

export const TIMEZONES = [
	'Europe/Andorra',
	'Asia/Dubai',
	'Asia/Kabul',
	'Europe/Tirane',
	'Asia/Yerevan',
	'Antarctica/Casey',
	'Antarctica/Davis',
	'Antarctica/DumontDUrville', // https://bugs.chromium.org/p/chromium/issues/detail?id=928068
	'Antarctica/Mawson',
	'Antarctica/Palmer',
	'Antarctica/Rothera',
	'Antarctica/Syowa',
	'Antarctica/Troll',
	'Antarctica/Vostok',
	'America/Argentina/Buenos_Aires',
	'America/Argentina/Cordoba',
	'America/Argentina/Salta',
	'America/Argentina/Jujuy',
	'America/Argentina/Tucuman',
	'America/Argentina/Catamarca',
	'America/Argentina/La_Rioja',
	'America/Argentina/San_Juan',
	'America/Argentina/Mendoza',
	'America/Argentina/San_Luis',
	'America/Argentina/Rio_Gallegos',
	'America/Argentina/Ushuaia',
	'Pacific/Pago_Pago',
	'Europe/Vienna',
	'Australia/Lord_Howe',
	'Antarctica/Macquarie',
	'Australia/Hobart',
	'Australia/Currie',
	'Australia/Melbourne',
	'Australia/Sydney',
	'Australia/Broken_Hill',
	'Australia/Brisbane',
	'Australia/Lindeman',
	'Australia/Adelaide',
	'Australia/Darwin',
	'Australia/Perth',
	'Australia/Eucla',
	'Asia/Baku',
	'America/Barbados',
	'Asia/Dhaka',
	'Europe/Brussels',
	'Europe/Sofia',
	'Atlantic/Bermuda',
	'Asia/Brunei',
	'America/La_Paz',
	'America/Noronha',
	'America/Belem',
	'America/Fortaleza',
	'America/Recife',
	'America/Araguaina',
	'America/Maceio',
	'America/Bahia',
	'America/Sao_Paulo',
	'America/Campo_Grande',
	'America/Cuiaba',
	'America/Santarem',
	'America/Porto_Velho',
	'America/Boa_Vista',
	'America/Manaus',
	'America/Eirunepe',
	'America/Rio_Branco',
	'America/Nassau',
	'Asia/Thimphu',
	'Europe/Minsk',
	'America/Belize',
	'America/St_Johns',
	'America/Halifax',
	'America/Glace_Bay',
	'America/Moncton',
	'America/Goose_Bay',
	'America/Blanc-Sablon',
	'America/Toronto',
	'America/Nipigon',
	'America/Thunder_Bay',
	'America/Iqaluit',
	'America/Pangnirtung',
	'America/Atikokan',
	'America/Winnipeg',
	'America/Rainy_River',
	'America/Resolute',
	'America/Rankin_Inlet',
	'America/Regina',
	'America/Swift_Current',
	'America/Edmonton',
	'America/Cambridge_Bay',
	'America/Yellowknife',
	'America/Inuvik',
	'America/Creston',
	'America/Dawson_Creek',
	'America/Fort_Nelson',
	'America/Vancouver',
	'America/Whitehorse',
	'America/Dawson',
	'Indian/Cocos',
	'Europe/Zurich',
	'Africa/Abidjan',
	'Pacific/Rarotonga',
	'America/Santiago',
	'America/Punta_Arenas',
	'Pacific/Easter',
	'Asia/Shanghai',
	'Asia/Urumqi',
	'America/Bogota',
	'America/Costa_Rica',
	'America/Havana',
	'Atlantic/Cape_Verde',
	'America/Curacao',
	'Indian/Christmas',
	'Asia/Nicosia',
	'Asia/Famagusta',
	'Europe/Prague',
	'Europe/Berlin',
	'Europe/Copenhagen',
	'America/Santo_Domingo',
	'Africa/Algiers',
	'America/Guayaquil',
	'Pacific/Galapagos',
	'Europe/Tallinn',
	'Africa/Cairo',
	'Africa/El_Aaiun',
	'Europe/Madrid',
	'Africa/Ceuta',
	'Atlantic/Canary',
	'Europe/Helsinki',
	'Pacific/Fiji',
	'Atlantic/Stanley',
	'Pacific/Chuuk',
	'Pacific/Pohnpei',
	'Pacific/Kosrae',
	'Atlantic/Faroe',
	'Europe/Paris',
	'Europe/London',
	'Asia/Tbilisi',
	'America/Cayenne',
	'Africa/Accra',
	'Europe/Gibraltar',
	'America/Godthab',
	'America/Danmarkshavn',
	'America/Scoresbysund',
	'America/Thule',
	'Europe/Athens',
	'Atlantic/South_Georgia',
	'America/Guatemala',
	'Pacific/Guam',
	'Africa/Bissau',
	'America/Guyana',
	'Asia/Hong_Kong',
	'America/Tegucigalpa',
	'America/Port-au-Prince',
	'Europe/Budapest',
	'Asia/Jakarta',
	'Asia/Pontianak',
	'Asia/Makassar',
	'Asia/Jayapura',
	'Europe/Dublin',
	'Asia/Jerusalem',
	'Asia/Kolkata',
	'Indian/Chagos',
	'Asia/Baghdad',
	'Asia/Tehran',
	'Atlantic/Reykjavik',
	'Europe/Rome',
	'America/Jamaica',
	'Asia/Amman',
	'Asia/Tokyo',
	'Africa/Nairobi',
	'Asia/Bishkek',
	'Pacific/Tarawa',
	'Pacific/Enderbury',
	'Pacific/Kiritimati',
	'Asia/Pyongyang',
	'Asia/Seoul',
	'Asia/Almaty',
	'Asia/Qyzylorda',
	'Asia/Qostanay', // https://bugs.chromium.org/p/chromium/issues/detail?id=928068
	'Asia/Aqtobe',
	'Asia/Aqtau',
	'Asia/Atyrau',
	'Asia/Oral',
	'Asia/Beirut',
	'Asia/Colombo',
	'Africa/Monrovia',
	'Europe/Vilnius',
	'Europe/Luxembourg',
	'Europe/Riga',
	'Africa/Tripoli',
	'Africa/Casablanca',
	'Europe/Monaco',
	'Europe/Chisinau',
	'Pacific/Majuro',
	'Pacific/Kwajalein',
	'Asia/Yangon',
	'Asia/Ulaanbaatar',
	'Asia/Hovd',
	'Asia/Choibalsan',
	'Asia/Macau',
	'America/Martinique',
	'Europe/Malta',
	'Indian/Mauritius',
	'Indian/Maldives',
	'America/Mexico_City',
	'America/Cancun',
	'America/Merida',
	'America/Monterrey',
	'America/Matamoros',
	'America/Mazatlan',
	'America/Chihuahua',
	'America/Ojinaga',
	'America/Hermosillo',
	'America/Tijuana',
	'America/Bahia_Banderas',
	'Asia/Kuala_Lumpur',
	'Asia/Kuching',
	'Africa/Maputo',
	'Africa/Windhoek',
	'Pacific/Noumea',
	'Pacific/Norfolk',
	'Africa/Lagos',
	'America/Managua',
	'Europe/Amsterdam',
	'Europe/Oslo',
	'Asia/Kathmandu',
	'Pacific/Nauru',
	'Pacific/Niue',
	'Pacific/Auckland',
	'Pacific/Chatham',
	'America/Panama',
	'America/Lima',
	'Pacific/Tahiti',
	'Pacific/Marquesas',
	'Pacific/Gambier',
	'Pacific/Port_Moresby',
	'Pacific/Bougainville',
	'Asia/Manila',
	'Asia/Karachi',
	'Europe/Warsaw',
	'America/Miquelon',
	'Pacific/Pitcairn',
	'America/Puerto_Rico',
	'Asia/Gaza',
	'Asia/Hebron',
	'Europe/Lisbon',
	'Atlantic/Madeira',
	'Atlantic/Azores',
	'Pacific/Palau',
	'America/Asuncion',
	'Asia/Qatar',
	'Indian/Reunion',
	'Europe/Bucharest',
	'Europe/Belgrade',
	'Europe/Kaliningrad',
	'Europe/Moscow',
	'Europe/Simferopol',
	'Europe/Kirov',
	'Europe/Astrakhan',
	'Europe/Volgograd',
	'Europe/Saratov',
	'Europe/Ulyanovsk',
	'Europe/Samara',
	'Asia/Yekaterinburg',
	'Asia/Omsk',
	'Asia/Novosibirsk',
	'Asia/Barnaul',
	'Asia/Tomsk',
	'Asia/Novokuznetsk',
	'Asia/Krasnoyarsk',
	'Asia/Irkutsk',
	'Asia/Chita',
	'Asia/Yakutsk',
	'Asia/Khandyga',
	'Asia/Vladivostok',
	'Asia/Ust-Nera',
	'Asia/Magadan',
	'Asia/Sakhalin',
	'Asia/Srednekolymsk',
	'Asia/Kamchatka',
	'Asia/Anadyr',
	'Asia/Riyadh',
	'Pacific/Guadalcanal',
	'Indian/Mahe',
	'Africa/Khartoum',
	'Europe/Stockholm',
	'Asia/Singapore',
	'America/Paramaribo',
	'Africa/Juba',
	'Africa/Sao_Tome',
	'America/El_Salvador',
	'Asia/Damascus',
	'America/Grand_Turk',
	'Africa/Ndjamena',
	'Indian/Kerguelen',
	'Asia/Bangkok',
	'Asia/Dushanbe',
	'Pacific/Fakaofo',
	'Asia/Dili',
	'Asia/Ashgabat',
	'Africa/Tunis',
	'Pacific/Tongatapu',
	'Europe/Istanbul',
	'America/Port_of_Spain',
	'Pacific/Funafuti',
	'Asia/Taipei',
	'Europe/Kiev',
	'Europe/Uzhgorod',
	'Europe/Zaporozhye',
	'Pacific/Wake',
	'America/New_York',
	'America/Detroit',
	'America/Kentucky/Louisville',
	'America/Kentucky/Monticello',
	'America/Indiana/Indianapolis',
	'America/Indiana/Vincennes',
	'America/Indiana/Winamac',
	'America/Indiana/Marengo',
	'America/Indiana/Petersburg',
	'America/Indiana/Vevay',
	'America/Chicago',
	'America/Indiana/Tell_City',
	'America/Indiana/Knox',
	'America/Menominee',
	'America/North_Dakota/Center',
	'America/North_Dakota/New_Salem',
	'America/North_Dakota/Beulah',
	'America/Denver',
	'America/Boise',
	'America/Phoenix',
	'America/Los_Angeles',
	'America/Anchorage',
	'America/Juneau',
	'America/Sitka',
	'America/Metlakatla',
	'America/Yakutat',
	'America/Nome',
	'America/Adak',
	'Pacific/Honolulu',
	'America/Montevideo',
	'Asia/Samarkand',
	'Asia/Tashkent',
	'America/Caracas',
	'Asia/Ho_Chi_Minh',
	'Pacific/Efate',
	'Pacific/Wallis',
	'Pacific/Apia',
	'Africa/Johannesburg',
];

export const getMenuItems = () => {
	const menuItems = [
		// { to: 'design-system', label: 'DS' },
		{ to: 'overview', label: __( 'Overview', 'easy-min-max' ) },
		{
			to: 'rules',
			label: __( 'Rules', 'easy-min-max' ),
		},
		// {
		// 	to: 'logs-analytics',
		// 	label: __( 'Analytics & Logs', 'easy-min-max' ),
		// },
		// { to: 'settings', label: __( 'Settings', 'easy-min-max' ) },
		// { divider: true },
		// {
		// 	to: 'plugins',
		// 	label: __( 'WPXPO Plugins', 'easy-min-max' ),
		// 	leftIcon: 'connect',
		// },
	];

	if ( showLicensePage() ) {
		menuItems.splice( 4, 0, {
			to: 'license',
			label: __( 'License', 'easy-min-max' ),
		} );
	}

	return menuItems;
};

export const PRO_FEATURES_LIST = [
	__( 'Create unlimited shipping rules', 'easy-min-max' ),
	__( 'Stack unlimited rule groups', 'easy-min-max' ),
	__( 'Fully unlocked carrier integrations', 'easy-min-max' ),
	__( 'Fully unlock table rates', 'easy-min-max' ),
	__( 'Unlock handling fees, visibility, and more!', 'easy-min-max' ),
];
